### ISSUE TITLE
Check input files etc for correct specification indications of UC_INDEX_RATIOS

### ISSUE THREAD

**Issue by hp115** [Erastova-group/ClayCode#45]
Should be like this:
```
# ----------------------------------------------------------------------------
# Optional: Unit Cell Composition and Ratios input
# if not given, these will be calculated from data in the CLAY_COMP .csv file
# (Default no UC_INDEX_RATIOS specified)
# -----------------------------------------------------------------------------

# required UC indices and their ratios (ratios(tot): 1.00)
UC_INDEX_RATIOS:
  1: 0.5
  2: 0.5

IL_ION_RATIOS:
  Na: 0.5
  Ca: 0.5

# -----------------------------------------------------------------------------
```
